name: protein_gibbs_sampler
channels:
  - defaults
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
dependencies:
  - python>=3.8
  - pandas~=1.3.5
  - muscle~=3.8.0
  - biopython~=1.79
  - tqdm~=4.62.0
  - pytorch~=1.9.0
  - cudatoolkit=11.1
  - mafft=7.487
  - hmmer~=3.3.2
  - pip
  - pytest
  - pytest-datadir
  - pip:
    - fair-esm~=0.4.2
    - -e .

